#!/bin/bash
#     ////     //  ////     //
#    // //    //  // //    //
#   //  //   //  //  //   //
#  //   //  //  //   //  //
# //    // //  //    // //
#//     ////  //     ////
#
#20200602 - Created script to remotely backup Files
#20200614 - Added confirmation that disks are mounted and logging file
#20201227 - Adopted for RemoteBackup
#20210418 - Corrected script for interview
#
echo "----------------------------"
echo "--[ Connecting WireGuard ]--"
echo "----------------------------"
sudo wg-quick up wg0
sudo wg
echo "----------------------------------------"
echo "--[ Mounting NNVault & NNRemoteBackup]--"
echo "----------------------------------------"
sudo mount -t cifs //10.0.100.10/NNVault /nnvault/ -o credentials=/home/nn/.smbnnvault
sudo mount -t cifs //192.168.100.10/NNRemoteBackup /nnremotebackup -o credentials=/home/nn/.smbnnremotebackup
echo "---------------------------------------------------"
echo "--[ Confirming NNVault & NNRemoteBackup mounted ]--"
echo "---------------------------------------------------"
if grep -qs '/nnvault ' /proc/mounts; then
  echo "NNVault Mounted"
    if grep -qs '/nnremotebackup ' /proc/mounts; then
      echo "NNRemoteBackup Mounted"
      echo "--------------------------------"
      echo "--[ Run Dry-Run Rsync? (y/n) ]--"
      echo "--------------------------------"
      read -p ""
      if [[ $REPLY =~ ^[Yy]$ ]]
      then
        sudo rsync -anzh --inplace --info=progress2 --delete-during --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /nnvault/Files/ /nnremotebackup/NNVault/Files/
      fi
      echo "-----------------------------"
      echo "--[ Run Real Rsync? (y/n) ]--"
      echo "-----------------------------"
      read -p ""
      if [[ $REPLY =~ ^[Yy]$ ]]
      then
        sudo rsync -azh --inplace --info=progress2 --delete-during --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /nnvault/Files/ /nnremotebackup/NNVault/Files/ --log-file=/nnvault/Backup/NNServer/HOME.RemoteBackup/logs/remote_backup_"$(date +%Y-%m-%d_%H%M%S)".log
        sudo find /nnvault/Backup/NNServer/HOME.RemoteBackup/logs/ -mtime +30 -exec rm -rf {} +
      fi
      else
      echo "Error : NNRemoteBackup Unmounted"
    fi
  else
  echo "Error : NNVault Unmounted"
fi
echo "-------------------------------------"
echo "--[ Disconnecting SMB & WireGuard ]--"
echo "-------------------------------------"
#Cleanup
sudo umount -t cifs //10.0.100.10/NNVault
sudo umount -t cifs //192.168.100.10/NNRemoteBackup
sudo wg-quick down wg0
sudo wg